### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adminlove520** [baiyz0825/corp-wechat-gptbot#3]
请问可信域名这块怎么处理呀   个人用户太难了

**Comment by baiyz0825** [comment]
不需要设置可信域名，只需要配置

1. 可信ip （微信早期的三方应用不需要可信ip，之后是需要的，如果是没有公网ip的情况下，你可以用其的三方代理或者自建代理，如果你有自己的服务器那就直接写自己的服务器就可以了）如果没有这个可信ip就不需要配置这一项
![image](https://user-images.githubusercontent.com/81071870/234338808-a7a11d65-ad21-46eb-82eb-ed76c372dbc2.png)

2. API回调地址即可
![image](https://user-images.githubusercontent.com/81071870/234338750-b0d86c7a-e592-4bc6-a467-3269ced140e3.png)
